version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    depends_on:
      - postgres_auth
    profiles:
      - dev
      - full

  postgres_auth:
    image: postgres:16
    environment:
      POSTGRES_DB: ksb_auth_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    profiles:
      - dev
      - full

  auth-service:
    build: ./auth-service
    ports:
      - "9001:9001"
    environment:
      DB_HOST: postgres_auth
      DB_PORT: 5432
      DB_NAME: ksb_auth_db
      DB_USER: admin
      DB_PASSWORD: password
    depends_on:
      - postgres_auth
      - keycloak
    profiles:
      - full

  postgres_notification:
    image: postgres:16
    environment:
      POSTGRES_DB: ksb_notification_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_notification_data:/var/lib/postgresql/data
    profiles:
      - dev
      - full

  notification-service:
    build: ./notification-service
    ports:
      - "9002:9002"
    environment:
      DB_HOST: postgres_notification
      DB_PORT: 5432
      DB_NAME: ksb_notification_db
      DB_USER: admin
      DB_PASSWORD: password
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
    depends_on:
      - postgres_notification
      - mailhog
    profiles:
      - full

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    profiles:
      - dev
      - full

volumes:
  postgres_auth_data:
  postgres_notification_data: