style:
  WildcardImport:
    active: false   # отключаем правило
    excludeImports: [] # можно исключить определённые wildcard импорты, если нужно

exceptions:
  TooGenericExceptionCaught:
    active: false