style:
  WildcardImport:
    active: false   # выключаем detekt-правило

formatting:
  active: true      # включаем поддержку ktlint-правил
  NoWildcardImports:
    active: false   # выключаем ktlint-правило